// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetSaude_Completo.Data;

#nullable disable

namespace PetSaude_Completo.Migrations
{
    [DbContext(typeof(PetSaude_CompletoContext))]
    [Migration("20260325095041_unidade")]
    partial class unidade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetSaude_Completo.Models.AgenteSaude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeAtendimentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeAtendimentoId");

                    b.ToTable("AgenteSaude");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AreaId");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Categoria", b =>
                {
                    b.Property<long>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoriaId"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Comorbidade", b =>
                {
                    b.Property<int>("ComorbidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComorbidadeId"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComorbidadeId");

                    b.ToTable("Comorbidade");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Frequencia", b =>
                {
                    b.Property<int>("FrequenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrequenciaId"));

                    b.Property<int>("Fator")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FrequenciaId");

                    b.ToTable("Frequencia");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Mensagem", b =>
                {
                    b.Property<int>("MensagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MensagemId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("FrequenciaMensagemId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HorarioEnvio")
                        .HasColumnType("time");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MensagemId");

                    b.HasIndex("AreaId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FrequenciaMensagemId");

                    b.ToTable("Mensagem");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.MensagemComorbidade", b =>
                {
                    b.Property<int>("MensagemId")
                        .HasColumnType("int");

                    b.Property<int>("ComorbidadeId")
                        .HasColumnType("int");

                    b.HasKey("MensagemId", "ComorbidadeId");

                    b.HasIndex("ComorbidadeId");

                    b.ToTable("MensagemComorbidade");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Microarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgenteSaudeId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeAtendimentoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgenteSaudeId")
                        .IsUnique()
                        .HasFilter("[AgenteSaudeId] IS NOT NULL");

                    b.HasIndex("UnidadeAtendimentoId");

                    b.ToTable("Microarea");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PacienteId"));

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Microarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MicroareaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PacienteId");

                    b.HasIndex("MicroareaId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.PacienteComorbidade", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("ComorbidadeId")
                        .HasColumnType("int");

                    b.HasKey("PacienteId", "ComorbidadeId");

                    b.HasIndex("ComorbidadeId");

                    b.ToTable("PacienteComorbidades");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.UnidadeAtendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("UnidadeAtendimento");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.AgenteSaude", b =>
                {
                    b.HasOne("PetSaude_Completo.Models.UnidadeAtendimento", "UnidadeAtendimento")
                        .WithMany()
                        .HasForeignKey("UnidadeAtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeAtendimento");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Mensagem", b =>
                {
                    b.HasOne("PetSaude_Completo.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetSaude_Completo.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetSaude_Completo.Models.Frequencia", "FrequenciaMensagem")
                        .WithMany()
                        .HasForeignKey("FrequenciaMensagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Categoria");

                    b.Navigation("FrequenciaMensagem");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.MensagemComorbidade", b =>
                {
                    b.HasOne("PetSaude_Completo.Models.Comorbidade", "Comorbidade")
                        .WithMany("MensagemComorbidades")
                        .HasForeignKey("ComorbidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetSaude_Completo.Models.Mensagem", "Mensagem")
                        .WithMany("MensagemComorbidades")
                        .HasForeignKey("MensagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comorbidade");

                    b.Navigation("Mensagem");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Microarea", b =>
                {
                    b.HasOne("PetSaude_Completo.Models.AgenteSaude", "AgenteSaude")
                        .WithOne("Microarea")
                        .HasForeignKey("PetSaude_Completo.Models.Microarea", "AgenteSaudeId");

                    b.HasOne("PetSaude_Completo.Models.UnidadeAtendimento", "UnidadeAtendimento")
                        .WithMany()
                        .HasForeignKey("UnidadeAtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgenteSaude");

                    b.Navigation("UnidadeAtendimento");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Paciente", b =>
                {
                    b.HasOne("PetSaude_Completo.Models.Microarea", null)
                        .WithMany("Pacientes")
                        .HasForeignKey("MicroareaId");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.PacienteComorbidade", b =>
                {
                    b.HasOne("PetSaude_Completo.Models.Comorbidade", "Comorbidade")
                        .WithMany("PacienteComorbidades")
                        .HasForeignKey("ComorbidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetSaude_Completo.Models.Paciente", "Paciente")
                        .WithMany("PacienteComorbidades")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comorbidade");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.UnidadeAtendimento", b =>
                {
                    b.HasOne("PetSaude_Completo.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.AgenteSaude", b =>
                {
                    b.Navigation("Microarea")
                        .IsRequired();
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Comorbidade", b =>
                {
                    b.Navigation("MensagemComorbidades");

                    b.Navigation("PacienteComorbidades");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Mensagem", b =>
                {
                    b.Navigation("MensagemComorbidades");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Microarea", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Paciente", b =>
                {
                    b.Navigation("PacienteComorbidades");
                });
#pragma warning restore 612, 618
        }
    }
}
