// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetSaude_Completo.Data;

#nullable disable

namespace PetSaude_Completo.Migrations
{
    [DbContext(typeof(PetSaude_CompletoContext))]
    [Migration("20260312191947_paciente")]
    partial class paciente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetSaude_Completo.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AreaId");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Categoria", b =>
                {
                    b.Property<long>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoriaId"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Comorbidade", b =>
                {
                    b.Property<int>("ComorbidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComorbidadeId"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComorbidadeId");

                    b.ToTable("Comorbidade");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Frequencia", b =>
                {
                    b.Property<int>("FrequenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrequenciaId"));

                    b.Property<int>("Fator")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FrequenciaId");

                    b.ToTable("Frequencia");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Mensagem", b =>
                {
                    b.Property<int>("MensagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MensagemId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("FrequenciaMensagemId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HorarioEnvio")
                        .HasColumnType("time");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MensagemId");

                    b.HasIndex("AreaId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FrequenciaMensagemId");

                    b.ToTable("Mensagem");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.MensagemComorbidade", b =>
                {
                    b.Property<int>("MensagemId")
                        .HasColumnType("int");

                    b.Property<int>("ComorbidadeId")
                        .HasColumnType("int");

                    b.HasKey("MensagemId", "ComorbidadeId");

                    b.HasIndex("ComorbidadeId");

                    b.ToTable("MensagemComorbidade");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Mensagem", b =>
                {
                    b.HasOne("PetSaude_Completo.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetSaude_Completo.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetSaude_Completo.Models.Frequencia", "FrequenciaMensagem")
                        .WithMany()
                        .HasForeignKey("FrequenciaMensagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Categoria");

                    b.Navigation("FrequenciaMensagem");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.MensagemComorbidade", b =>
                {
                    b.HasOne("PetSaude_Completo.Models.Comorbidade", "Comorbidade")
                        .WithMany("MensagemComorbidades")
                        .HasForeignKey("ComorbidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetSaude_Completo.Models.Mensagem", "Mensagem")
                        .WithMany("MensagemComorbidades")
                        .HasForeignKey("MensagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comorbidade");

                    b.Navigation("Mensagem");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Comorbidade", b =>
                {
                    b.Navigation("MensagemComorbidades");
                });

            modelBuilder.Entity("PetSaude_Completo.Models.Mensagem", b =>
                {
                    b.Navigation("MensagemComorbidades");
                });
#pragma warning restore 612, 618
        }
    }
}
